name: git-validate

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: setup node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: validate git
      run: |
        npm ci
        npm run lint:commits
      env:
        CI: true
